### ISSUE TITLE
hypercube plotters fail with Axes3DSubplot AttributeError

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/mystic#152]
```
>>> import mystic as my
>>> my.support.hypercube('paramlog.py')
<string>:229: MatplotlibDeprecationWarning: Axes3D(fig) adding itself to the figure is deprecated since 3.4. Pass the keyword argument auto_add_to_figure=False and use fig.add_axes(ax) to suppress this warning. The default value of auto_add_to_figure will change to False in mpl3.5 and True values will no longer work in 3.6.  This is consistent with other Axes classes.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 229, in hypercube
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/matplotlib/axes/_subplots.py", line 38, in __init__
    self.set_subplotspec(SubplotSpec._from_subplot_args(fig, args))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/matplotlib/gridspec.py", line 660, in _from_subplot_args
    gs = GridSpec._check_gridspec_exists(figure, rows, cols)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/matplotlib/gridspec.py", line 214, in _check_gridspec_exists
    gs = ax.get_subplotspec().get_gridspec()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/matplotlib/axes/_subplots.py", line 67, in get_subplotspec
    return self._subplotspec
AttributeError: 'Axes3DSubplot' object has no attribute '_subplotspec'
```
This only seems to happen when the following is used:
```
    from mpl_toolkits.mplot3d import Axes3D as _Axes3D
    from matplotlib.axes import subplot_class_factory
    Subplot3D = subplot_class_factory(_Axes3D)
```

**Comment by mmckerns** [comment]
Actually, this snippet reproduces the error:
```
Python 3.7.12 (default, Nov 11 2021, 17:34:58) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot as plt
>>> from mpl_toolkits.mplot3d import Axes3D as _Axes3D
>>> from matplotlib.axes import subplot_class_factory
>>> Subplot3D = subplot_class_factory(_Axes3D)
>>> fig = plt.figure()
>>> ax1 = Subplot3D(fig, 1,1,1)
__main__:1: MatplotlibDeprecationWarning: Axes3D(fig) adding itself to the figure is deprecated since 3.4. Pass the keyword argument auto_add_to_figure=False and use fig.add_axes(ax) to suppress this warning. The default value of auto_add_to_figure will change to False in mpl3.5 and True values will no longer work in 3.6.  This is consistent with other Axes classes.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/axes/_subplots.py", line 36, in __init__
    self.set_subplotspec(SubplotSpec._from_subplot_args(fig, args))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/gridspec.py", line 595, in _from_subplot_args
    gs = GridSpec._check_gridspec_exists(figure, rows, cols)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/gridspec.py", line 212, in _check_gridspec_exists
    gs = ax.get_subplotspec().get_gridspec()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/axes/_subplots.py", line 56, in get_subplotspec
    return self._subplotspec
AttributeError: 'Axes3DSubplot' object has no attribute '_subplotspec'
```
